//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pescador.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public string ServiceUserName { get; set; }
        public string ServicePassword { get; set; }
        public string ServiceUrl { get; set; }
        public int ServiceTimeout { get; set; }
        public int ServiceRetrySeconds { get; set; }
        public int ID { get; set; }
    }
}
