//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pescador.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public Destination()
        {
            this.Trucks = new HashSet<Truck>();
        }
    
        public int ID { get; set; }
        public string Destination1 { get; set; }
    
        public virtual ICollection<Truck> Trucks { get; set; }
    }
}
